### ISSUE TITLE
XQueue will be deprecated in Oct. 2024

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/tutor-xqueue#20]
I'm opening this issue just to spread the word that the upstream xqueue repo is being deprecated:
* forums: https://discuss.openedx.org/t/deprecation-xqueue-xqueue-watcher/10932
* issue: https://github.com/openedx/public-engineering/issues/214

Any objections to the deprecation?

Should we deprecate this repo too?

**Comment by regisb** [comment]
Good point. Let's wait until the deprecation decision, and then we'll put this repository in maintenance mode.

**Comment by regisb** [comment]
Deprecation is postponed for a year.

**Comment by regisb** [comment]
Let's close this and re-open next year.
