### ISSUE TITLE
tutor-xqueue codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-xqueue#29]
- [x] Ensure tutor-xqueue codebase is compatible with Python 3.12
- [x] Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly. This task would rely on upgrade of xqueue to Python 3.12

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by DawoudSheraz** [comment]
FYI @jfavellar90. Please let me know if you need any assistance or information. Thanks

**Comment by DawoudSheraz** [comment]
@jfavellar90 FYI -- Reminder

**Comment by jfavellar90** [comment]
@DawoudSheraz Hi, This is to report that the Xqueue codebase is still in progress to be migrated to [Python 3.12](https://github.com/openedx/xqueue/issues/926). I'll try to provide support or push a bit on that side to get that task completed. On the Tutor plugin side, I'll try to build the image with Python 3.12 from the branch related to this [PR](https://github.com/openedx/xqueue/pull/923) and check if it's functional.
