### ISSUE TITLE
Ubuntu 24.04 Upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-xqueue#32]
- Ensure CI uses the latest ubuntu
- Ensure dockerfile is updated to use ubuntu 24.04
- Ensure any documentation/references are updated
- Ensure the change works as expected post-upstream release

See https://github.com/overhangio/tutor/issues/1113 for context.
Additionally, tutor-xqueu moved to a different base image in https://github.com/overhangio/tutor-xqueue/pull/30. We would need to revert that to ensure tutor plugin has same config specs as upstream.

**Comment by jfavellar90** [comment]
@DawoudSheraz can we close this issue?

**Comment by DawoudSheraz** [comment]
> @DawoudSheraz can we close this issue?

Yes. Since the upsteam is testing its CI on latest ubuntu, we don't need to wait for anything from upstream.
